name: can_usb
description: >-
  A Flutter package for USB-CANFD communication over serial (UART/USB-CDC),
  with a frame builder/parser and a high-level CanusbDevice API.
version: 0.1.3
homepage: https://github.com/sicrisembay/flutter_packages/tree/main/packages/can_usb
repository: https://github.com/sicrisembay/flutter_packages/tree/main/packages/can_usb
issue_tracker: https://github.com/sicrisembay/flutter_packages/issues
topics:
  - can-bus
  - serial
  - hardware
  - iot

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_libserialport: ^0.6.0
  synchronized: ^3.4.0
  usb_serial: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
